title: Juncture
tagline: A Visual Essay Site
banner: https://picsum.photos/1000/400
#favicon:
#logo: 

# When using a custom domain these fields must be updated to match
# the account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: User guide
  icon: fas fa-info
  action: load-page
  path: /user-guide
- label: Contact Us
  icon: fas fa-envelope
  action: contact-us
- label:
- label: View page source
  icon: fas fa-file-code
  action: view-markdown

# If a contact-us action is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
#contactForm:
#  to:
#  - User Name <user@example.com>
#  subject: Contact Us
